kind: pipeline
type: docker
name: default

trigger:
  branch:
    exclude:
    - data

steps:

- name: selenium
  image: selenium/standalone-chrome
  detach: true

- name: getData
  image: 2edcovid/python_data_scraping:latest
  environment:
    APIKEY:
      from_secret: reddit_secret
    APIID:
      from_secret: reddit_client
    APIPWD:
      from_secret: reddit_pwd
    SSHKEY:
      from_secret: gsheet_ssh_key
    IMGUR_APIKEY:
      from_secret: imgur_key
  commands:
  - git fetch origin data:data
  - python fetchDataFiles.py
  - python stripData.py
  - python gsheetInteraction.py
  - python redditPost.py
  - python imgurPost.py
  - python commitChecker.py

- name: pushData
  image: appleboy/drone-git-push
  when:
    branch: [master]
  settings:
    ssh_key:
      from_secret: ssh_key
    remote_name: origin2
    remote: git@github.com:2edcovid/CovidDataAutomation.git
    branch: data
    local_ref: data


image_pull_secrets:
  - dockerconfig
